In [1]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)


2026-01-05 20:59:23.645178: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
/home/x13/.local/lib/python3.12/site-packages/keras/src/export/tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):


TensorFlow version: 2.20.0


In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0


In [3]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])


/home/x13/.local/lib/python3.12/site-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)
2026-01-05 20:59:26.417517: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)


In [4]:
predictions = model(x_train[:1]).numpy()
predictions


array([[ 0.19396296, -0.18248415,  0.2505951 , -0.05839898,  0.32506144,
        -0.05325411,  0.5970479 ,  0.4038246 ,  0.05290318, -0.2282797 ]],
      dtype=float32)

In [5]:
tf.nn.softmax(predictions).numpy()


array([[0.10312968, 0.07077742, 0.10913868, 0.08012799, 0.11757608,
        0.0805413 , 0.15432675, 0.12721121, 0.08956166, 0.06760923]],
      dtype=float32)

In [6]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)


In [7]:
loss_fn(y_train[:1], predictions).numpy()


np.float32(2.5189853)

In [8]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])


In [9]:
model.fit(x_train, y_train, epochs=5)


Epoch 1/5


2026-01-05 20:59:27.032290: W external/local_xla/xla/tsl/framework/cpu_allocator_impl.cc:84] Allocation of 188160000 exceeds 10% of free system memory.


1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9132 - loss: 0.2998
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9558 - loss: 0.1468
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9660 - loss: 0.1098
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9723 - loss: 0.0913
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9757 - loss: 0.0776


In [10]:
model.evaluate(x_test,  y_test, verbose=2)


313/313 - 0s - 1ms/step - accuracy: 0.9773 - loss: 0.0747


[0.07474615424871445, 0.9772999882698059]

In [11]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])


In [12]:
probability_model(x_test[:5])


<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[2.3621160e-07, 6.7729964e-09, 2.6141045e-06, 9.8750766e-05,
        1.3262330e-11, 4.1299039e-08, 3.1068335e-14, 9.9989653e-01,
        5.9929249e-07, 1.3241132e-06],
       [3.4800396e-09, 1.1640988e-05, 9.9998558e-01, 2.6438504e-06,
        2.0201091e-17, 5.5704295e-09, 8.2187865e-09, 4.7078773e-15,
        1.2447613e-07, 1.1275881e-13],
       [5.8765519e-08, 9.9959105e-01, 4.3709228e-05, 6.8380461e-07,
        3.2923597e-06, 5.1020669e-07, 2.4640908e-06, 3.3227706e-04,
        2.5412855e-05, 5.1507016e-07],
       [9.9999261e-01, 1.6311914e-09, 6.5048444e-06, 3.9385584e-09,
        5.2113847e-10, 4.5766420e-08, 4.6990525e-07, 1.4339052e-07,
        4.0963593e-09, 8.4944737e-08],
       [7.0472420e-06, 4.7089038e-10, 7.6873357e-06, 9.2339739e-08,
        9.9890459e-01, 1.1224202e-05, 2.7674421e-05, 9.3218572e-05,
        1.0280813e-06, 9.4749202e-04]], dtype=float32)>